### ISSUE TITLE
Update 'Capacity' field to take actual facility capacity

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#203]
**Is your feature request related to a problem? Please describe.**
We currently ask the user to enter the % their facility is over or under capacity, forcing them to perform this calculation themselves.

However, the capacity of a facility is a known and static thing, and is easier for them to provide once then forget about. We should be calculating over/under capacity based on that.

**Describe the solution you'd like**
Update the 'Capacity' box to ask for the facility's capacity, instead of for how far above or below it they are. Then use that to calculate ourselves from the population they've entered.

**Additional context**
- This is also generally useful information to us
- Easier input for the user / set-and-forget.

**Comment by daschi** [comment]
@cawarren I have a couple questions about this issue, is the image below the section in the facility form we want to change? Is the capacity a data point we have available from the public data, or would the change be request the capacity number here instead of "Occupancy Rate" ? Thanks for your help!

![image](https://user-images.githubusercontent.com/5402804/82858093-bc1e3c00-9ec7-11ea-8575-1677ea6d1023.png)
