### ISSUE TITLE
Dismissed promo flags don't stay dismissed.

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#309]
**Describe the bug**
Dismissed promo messages in the scenario sidebar return again upon subsequent page visits. The status is not persisted to the database.

**To Reproduce**

1. Go to the homepage. You need to have an un-dismissed promo box to see this error.
2. Click on 'dismiss' in the promo box
3. Reload the apge
4. See error: the same promo box reappears.

**Expected behavior**
The promo box does not reappear once dismissed.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: macOS catalina
- Browser [e.g. chrome, edge]: Firefox
- Version [e.g. 22]: latest

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]:
- OS: [e.g. iOS8.1]:
- Browser [e.g. stock browser, safari]:
- Version [e.g. 22]:

**Additional context**
Pretty sure this is related to some conditional save behavior in the `ScenarioSidebar` component: https://github.com/Recidiviz/covid19-dashboard/blob/master/src/page-multi-facility/ScenarioSidebar.tsx#L55

**Comment by jessex** [comment]
Hm, is this Firefox specific again, @macfarlandian? I don't see these error myself in Chrome.

**Comment by macfarlandian** [comment]
no I have seen it in chrome as well

**Comment by jessex** [comment]
Edit: The example below was in **production**. When I tried to do it on **master**, I found that the new promo which is now the first one, about adding case counts, does not get its status flag updated in Firebase on dismiss, and thus keeps reappearing. So this bug does exist on master, just not on production. This needs to be fixed before we can push a new release, so I'm sending it to the top of the backlog.

I just tried to reproduce from a fresh state and was unable to reproduce this in Chrome:
1. I cleared all of the promoStatus flags for my baseline scenario in Firebase by setting them all back to true, and I switched off both toggles
1. I reloaded the scenario details page and the daily reports promo was visible
1. I clicked _Dismiss_ on that promo, checked Firebase and it had been changed to false
1. I refreshed the page and that first promo was gone, and the next promo, the data sharing promo, was now visible
1. I clicked _Dismiss_ on the second promo, checked Firebase and it had also been changed to false
1. I refreshed the page and the second promo was no longer visible and the third promo did not show because I have too many facility models in the scenario for it to show
