### ISSUE TITLE
Encountered error while attempting to retrieve facilities upon landing on model.recidiviz.org

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#346]
**Describe the bug**
Facilities do not load upon landing on model.recidiviz.org. Console reveals 2 errors:
- Encountered error while attempting to retrieve facilities
- TypeError: Cannot read property 'toDate' of undefined

**To Reproduce**
go to: model.recidiviz.org
Previously I had entered 2-3 test facilities of data but don't recall all the data entered in those facilities.

**Expected behavior**
Facilities load

**Screenshots**
![image](https://user-images.githubusercontent.com/6633887/81430753-99e59980-9125-11ea-80f0-aab6474e0e07.png)

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: MacOS Catalina Version 10.15.3
- Browser [e.g. chrome, edge]: Chrome
- Version [e.g. 22]: 81.0.4044.138

**Additional context**
Issue began occurring after R(t) launch.

**Comment by jessex** [comment]
This has been fixed manually. The issue was that at the time of the Rt launch, one of the changes i the release introduced updatedAt and observedAt timestamps to `facility.modelInputs` in a backwards-incompatible manner. There was no offline or runtime migration performed, either, so some set of old facility models in the database were left with `modelInputs` that had none of the required timestamps.

After discussing possible code remediations with @sprad, we concluded it would be safer and ideal if the data itself was cleaned up instead of defaulting to some other timestamp and potentially introducing unwanted side-effects. So I walked the DB by hand and looked at every entity to be extra safe (I originally tried to script it but ran into permissions issues, a sign that our permissions model is working well). I found only `facility.modelInputs` objects with issues, across about a half dozen scenarios, all very old ones. There were no instances of `scenario` or `modelVersions` objects without the required timestamps.

Let this be a lesson to us to consider our schema migrations _very carefully_, no matter how fast we need to move.
