### ISSUE TITLE
Incorporate entering/exiting population into the model

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#61]
Population inputs should adjust to facility has X people entering, Y people leaving per day. Refer to master spreadsheet for implementation approach

**Comment by cawarren** [comment]
This is no longer blocked on data science.

You can see the implementation in [this model copy](https://docs.google.com/spreadsheets/d/1rptz00ZR_XJW9BtpeXH4bSPtHM6dGJAJZmzO8XQ6RpM/edit?usp=sharing) - the input is on the Inputs sheet, cell M43, and the updated population is calculated in the Calculations Data sheet, in cells B127-B138. Note that the output is on the Calculations tab - the way this was originally implemented, a macro copy/pasted it over the inputs when the user checked a checkbox. We don't need to do that, we can just adjust the inputs if the user enters any input at all for the turnover rate.

Please use the strings / copy in our doc, rather than the copy in this spreadsheet.

**Comment by macfarlandian** [comment]
@cawarren I see how it's being calculated in that sheet, but I can't really tell how it's being used ... can you point me in the right direction?

**Comment by cawarren** [comment]
Sorry, there was a macro in the original Excel that didn't make the leap into the Google sheet. Mainly what the macro did was tried to copy/paste the outputs in the Calculation Data sheet back into the Inputs sheet, to overwrite the total population numbers (Calculation Data B131-B138 --> Inputs M32-M39 and Calculation Data B130 --> Inputs M40).

So it's meant for those outputs at the bottom of Calculation Data to be used in place of the population totals provided in the inputs.

**Comment by macfarlandian** [comment]
ok - so it just adjusts the initial population figures, it's not a rolling change that continues adjusting the population every day? That doesn't totally make sense to me honestly ... if the user is explicitly entering the age breakdown numbers as current population figures, why would we override them?
